USE [master]
GO

/****** Object:  Database [db_winicg]    Script Date: 8/8/2023 9:37:27 PM ******/
CREATE DATABASE [db_winicg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_winicg', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_winicg.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_winicg_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_winicg_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_winicg].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_winicg] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_winicg] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_winicg] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_winicg] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_winicg] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_winicg] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [db_winicg] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_winicg] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_winicg] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_winicg] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_winicg] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_winicg] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_winicg] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_winicg] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_winicg] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_winicg] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_winicg] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_winicg] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_winicg] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_winicg] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_winicg] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_winicg] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_winicg] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_winicg] SET  MULTI_USER 
GO

ALTER DATABASE [db_winicg] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_winicg] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_winicg] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_winicg] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_winicg] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_winicg] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [db_winicg] SET QUERY_STORE = ON
GO

ALTER DATABASE [db_winicg] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [db_winicg] SET  READ_WRITE 
GO

